name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Enable Firebase webframeworks experiment
        run: firebase experiments:enable webframeworks

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//0g4JNuo9wUt-NCgYIARAAGBASNwF-L9IrBjxj_rJ-4g7mioX_7SWe6PlYZZd6YIjn5yPgYF1ZS78m1jnbrq6f8oJVbczbBiNJuAw
